/*
 * This source file was generated by the Gradle 'init' task
 */
package org.github.itzswirlz.isleportablelwjgl;

public class IsleApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new IsleApp().getGreeting());
    }
}
