/*
 * This source file was generated by the Gradle 'init' task
 */
package org.github.itzswirlz.isleportablelwjgl.isle;

import org.github.itzswirlz.isleportablelwjgl.lego1.LEGO1;

public class IsleApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new IsleApp().getGreeting());

        // Simple test
        LEGO1.MxVideoParam videoParam = new LEGO1.MxVideoParam();
        System.out.println("Video param addr: " + videoParam.address());
    }
}
